blank_issues_enabled: true
contact_links:
  - name: 游닄 Dokumentace
    url: https://github.com/LukasOrcik/upgates-com-mcp/blob/main/README.md
    about: P콏e캜t캩te si dokumentaci p콏ed vytvo콏en칤m issue
  - name: 游눫 Diskuze
    url: https://github.com/LukasOrcik/upgates-com-mcp/discussions
    about: M치te ot치zku? Zahajte diskuzi
  - name: 游꿡 Upgates Discord
    url: https://discord.gg/6X7VbMEVjk
    about: Upgates API v칳voj치콏sk치 komunita
  - name: 游닀 Upgates API Dokumentace
    url: https://upgatesapiv2.docs.apiary.io/
    about: Ofici치ln칤 Upgates API v2 dokumentace
  - name: 游깷 OpenMCP
    url: https://openmcp.cz
    about: Nav코tivte neziskov칳 projekt OpenMCP
