name: 游 Vylep코en칤 / Improvement
description: Navrhn캩te vylep코en칤 existuj칤c칤 funkcionality
title: "[IMPROVEMENT]: "
labels: ["enhancement", "improvement"]
body:
  - type: markdown
    attributes:
      value: |
        D캩kujeme za v치코 n치vrh na vylep코en칤! Popi코te, co by se m캩lo zlep코it.

  - type: dropdown
    id: area
    attributes:
      label: Oblast vylep코en칤
      description: 캛eho se vylep코en칤 t칳k치?
      options:
        - V칳kon / Performance
        - Dokumentace
        - Chybov칠 hl치코en칤 / Error messages
        - API design
        - U쬴vatelsk치 p콏칤v캩tivost (UX)
        - Kvalita k칩du
        - Testov치n칤
        - Bezpe캜nost
        - Anonymizace dat
        - Detail m칩dy
        - Filtrov치n칤
        - Export dat
        - Logov치n칤
        - Konfigurace
        - Jin칠
    validations:
      required: true

  - type: textarea
    id: current
    attributes:
      label: Sou캜asn칳 stav
      description: Jak to funguje te캞?
      placeholder: |
        Moment치ln캩 kdy...
        N치stroj XYZ...
    validations:
      required: true

  - type: textarea
    id: proposed
    attributes:
      label: Navrhovan칠 vylep코en칤
      description: Jak by to m캩lo fungovat po vylep코en칤?
      placeholder: |
        Bylo by lep코칤, kdyby...
        N치vrh: zm캩nit XYZ na...
    validations:
      required: true

  - type: textarea
    id: benefits
    attributes:
      label: P콏칤nosy vylep코en칤
      description: Pro캜 je toto vylep코en칤 d콢le쬴t칠?
      placeholder: |
        - Zrychl칤 to...
        - Zp콏ehledn칤 to...
        - Sn칤쮂 to spot콏ebu...
        - Vylep코칤 to u쬴vatelsk칳 z치쬴tek...
    validations:
      required: true

  - type: dropdown
    id: impact
    attributes:
      label: Dopad na u쬴vatele
      description: Koho vylep코en칤 ovlivn칤?
      multiple: true
      options:
        - V코echny u쬴vatele
        - E-shop majitele
        - E-commerce mana쬰ry
        - V칳voj치콏e integrac칤
        - AI/LLM pou쬴t칤
        - Pokro캜il칠 u쬴vatele
        - Za캜치te캜n칤ky

  - type: dropdown
    id: breaking
    attributes:
      label: Breaking change?
      description: Zp콢sob칤 vylep코en칤 nekompatibilitu s p콏edchoz칤mi verzemi?
      options:
        - Ne - zp캩tn캩 kompatibiln칤
        - Ano - bude pot콏eba aktualizovat konfiguraci
        - Ano - zm캩n칤 se API
        - Nejsem si jist칳/치
    validations:
      required: true

  - type: textarea
    id: example
    attributes:
      label: P콏칤klad pou쬴t칤
      description: Uka쬾e konkr칠tn칤 p콏칤klad p콏ed a po
      placeholder: |
        P콎ED:
        ```json
        { "detail": "full", "includeItems": true }
        ```

        PO vylep코en칤:
        ```json
        { "detail": "audit-fast" }  // automaticky includes items
        ```

  - type: textarea
    id: implementation
    attributes:
      label: N치vrh implementace (voliteln칠)
      description: M치te n치pad, jak by se to m캩lo implementovat?
      placeholder: |
        Mohlo by se to ud캩lat tak, 쬰...
        M칤sto X pou쮂셦 Y...

  - type: input
    id: related-tool
    attributes:
      label: Souvisej칤c칤 n치stroj/funkce
      description: Kter칠 캜치sti projektu se vylep코en칤 t칳k치?
      placeholder: nap콏. list_orders, token optimization, anonymizace

  - type: textarea
    id: alternatives
    attributes:
      label: Zva쬺van칠 alternativy
      description: Uva쬺vali jste o jin칳ch zp콢sobech vylep코en칤?
      placeholder: |
        Alternativn캩 by se mohlo...
        M칤sto toho jsem zva쬺val/a...

  - type: dropdown
    id: priority
    attributes:
      label: Priorita (v치코 n치zor)
      description: Jak nal칠hav칠 je toto vylep코en칤?
      options:
        - Kritick치 - blokuje pou쮂셨치n칤
        - Vysok치 - v칳znamn캩 by pomohlo
        - St콏edn칤 - bylo by to p콏칤jemn칠
        - N칤zk치 - drobn칠 vylep코en칤
    validations:
      required: true

  - type: textarea
    id: metrics
    attributes:
      label: Metriky 칰sp캩chu
      description: Jak pozn치me, 쬰 vylep코en칤 je 칰sp캩코n칠?
      placeholder: |
        - Zrychlen칤 o X%
        - Sn칤쬰n칤 spot콏eby token콢 o Y%
        - Pozitivn칤 feedback od Z u쬴vatel콢

  - type: textarea
    id: context
    attributes:
      label: Dal코칤 kontext
      description: Dal코칤 informace, odkazy, screenshots...
      placeholder: |
        Souvisej칤c칤 issues: #123
        Benchmark v칳sledky...
        P콏칤klady z jin칳ch projekt콢...

  - type: checkboxes
    id: contribution
    attributes:
      label: Ochota p콏isp캩t
      options:
        - label: Mohu pomoci s implementac칤
          required: false
        - label: Mohu pomoci s testov치n칤m
          required: false
        - label: Mohu pomoci s dokumentac칤
          required: false

  - type: checkboxes
    id: terms
    attributes:
      label: Kontroln칤 seznam
      options:
        - label: Zkontroloval/a jsem existuj칤c칤 issues
          required: true
        - label: Vylep코en칤 je v souladu s c칤li projektu
          required: true
